name: Build and Push Docker image

on:
  push:
    tags:
      - 'v*' # run only on tags like v1.0.0
  workflow_dispatch: # allow manual runs

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./roadrunner-php/8.4
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            edvin/roadrunner-php:8.4
            edvin/roadrunner-php:latest
